[profile.default]
solc-version = "0.8.15"
optimizer = false # faster compilation
optimizer-runs = 10_000_000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.default.fmt]
line_length = 80
tab_width = 2
bracket_spacing = false
int_types = 'short'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'thousands'

[invariant]
runs = 100              # The number of calls to make in the invariant tests
depth = 10              # The number of times to run the invariant tests
call_override = false   # Override calls
fail_on_revert = true  # Fail the test if the contract reverts
